### ISSUE TITLE
Continue to use timer for manual control

### ISSUE THREAD

**Issue by johnnyguitar77** [SwiCago/HarviaWiFi#12]
Hello,
Thank you for all your work, however I was wanting to implement this project and it seems like manual control is lost. I am hoping to combine manual control with wireless control at the same time. I was wondering if the following wire diagram made sense to you where the timer is kept in parallel with the Sonoff and the sauna thermometer is not removed. I understand that that would mean that one wouldn't be able to exceed the manually set temperature through wireless control, but that would be fine for me:
![schematic](https://user-images.githubusercontent.com/96360311/146660552-6efae2b6-6edb-4dbd-9740-3b8738578bad.png)

Also, if this wiring schematic makes sense, do you know which gauge wires I should use?

Thank you again for all the work you've done on this project. I think it's great to be able to add wireless control to these Harvia heaters.

**Comment by SwiCago** [comment]
Hi @johnnyguitar77 sorry for not seeing this question earlier. Yes you could wire it like this and preserve the original timer. You could also add keep the thermostat too as you have, set it to its highest setting and then wifi can still control temperature and on/off state. Like this in theory you can still use manual controls or wifi. 
No granted you will not be able to go higher than US regulation temps with the manual thermostat still in place. As for wiring size, 12ga is what you would use.

I may update my readme with this alternative, in case someone wants to do the same as you.
