### ISSUE TITLE
TH16 installation

### ISSUE THREAD

**Issue by xmozart** [SwiCago/HarviaWiFi#14]
Where did you install the Sonoff TH16 unit? You can't put it inside the heater, cause it is too hot. And you can't put it outside of the sauna, cause it could be too cold. So wondering where to put it.

**Comment by SwiCago** [comment]
It is in the electrical box on the outside of my sauna. Look at pic, right side. The wires for L1,L2 and R to sonoff are routed through conduit between the box and the block mounted in the heater
