### ISSUE TITLE
Not so much an issue...but how do I utilize json files in resources folder?

### ISSUE THREAD

**Issue by robschwieb** [SwiCago/HarviaWiFi#15]
@SwiCago Love the project! 

Quick question as I now have my TH16 flashed and MQTT docker up and running. Everything was really straight forward until I got to the MQTT Dash app...I have no clue what I'm doing.

I feel like I need to load the json files into the app but don't see a way to do that?

Any help would be appreciated and sorry to create an issue just for this!

**Comment by SwiCago** [comment]
In the APP, after you have created the initial entry that has the address to your MQTT broker. You click on it and it should be empty.
At the top, there is a Up/Down arrow button. Click subcribe and wait for metrics.
Then use https://github.com/SwiCago/HarviaWiFi/blob/master/resources/MQTT_DASH_Config_command_Line.txt
to send the json config for MQTT
