### ISSUE TITLE
A much easier way.

### ISSUE THREAD

**Issue by jsk1000** [SwiCago/HarviaWiFi#7]
Here's what I did and it works great.  I bypassed the switch on my heater so the heater is permanently on.

Bought a Lutron switch on Amazon to send power to the heater via wifi and a on/off switch on my phone.

The Lutron app has an 'on/off' schedule on my phone.  So when I enter the sauna, I set the timer on my phone to automatically turn the heater off 25 minutes later.  This is an important safety feature because my sauna gets up to 220 degrees.  If I passed out in there, I would cook.

**Comment by SwiCago** [comment]
Good for you, but looks like you have no temperature control and also sounds like you disabled the limiter that is built into the sauna, hence your sauna getting up to 220 degrees. You way might be easy, but very dangerous and could cause a fire. Good luck with that. My way was reviewed by Harvia(owners of Almost Heavenly sauna) and deemed good...hence why they blogged about it on their page. https://almostheaven.com/2019/02/remote-start-interview-2/

**Comment by sendtoworthington** [comment]
> Here's what I did and it works great. I bypassed the switch on my heater so the heater is permanently on.
> 
> Bought a Lutron switch on Amazon to send power to the heater via wifi and a on/off switch on my phone.
> 
> The Lutron app has an 'on/off' schedule on my phone. So when I enter the sauna, I set the timer on my phone to automatically turn the heater off 25 minutes later. This is an important safety feature because my sauna gets up to 220 degrees. If I passed out in there, I would cook.

Hi, could you give me more detail how you bypassed the switch? I wanted to get a lutron switch (120v) too, but I don't know which wires to bypass. Any info you have would be useful.

**Comment by jsk1000** [comment]
I had an electrician bypass the "dial".  There is a 60 minute dial timer on the sauna.

Note:  It is safter to have the dial.  If a person were to pass out there, that would be dangerous.  But I have had this set up since 2021.

**Comment by sendtoworthington** [comment]
I was following the github guide of the schematic - I was curious if you knew what amp the timer circuit was- I have a caseta system and I was thinking if the caseta switch could work since this can be set up to automatically turn off at a scheduled time.

It's nice your electrician went with it. I'm meeting one tomorrow who hopefully will agree to bypass it.

Thanks!

Jun 30, 2025 6:33:48 PM Jack Kanefield ***@***.***>:
